### PR TITLE
inscriptions.json

### PR DESCRIPTION
**Pull request by banqueiro**

### CODE REVIEW

**Comment by cloud6605** [comment]
Hi, also need meta.json file for this collection. @banqueiro

**Comment by cloud6605** [comment]
And you should put your folder under "collections" directory.

**Comment by banqueiro** [comment]
thanks for the guidance. is created.

**Comment by banqueiro** [comment]
here fam, 

meta.json #94  > https://github.com/unisat-wallet/fractal-ordinals-collections/pull/94 
Create Fractal_Dog #103   > https://github.com/unisat-wallet/fractal-ordinals-collections/pull/103

**Pull request closed without merging**
