### PR TITLE
Fractal Coin for the Fractal Bitcoin community

### PR DESCRIPTION
**Pull request by Fractoshi-Nakamoto**
99 Fractal Coin on Fractal ₿itcoin!

### CODE REVIEW

**Comment by cloud6605** [comment]
Hi, may you submit it once your collection is minted out? There's only inscriptions now. You still need to update the inscriptions.json file once the mint is over. @Fractoshi-Nakamoto

**Comment by Fractoshi-Nakamoto** [comment]
Hi!

All items are already inscribed (99 on unisat market only).

**Comment by cloud6605** [comment]
Sorry, the website in the meta.json isn't yours. And please add your twitter or discount link. @Fractoshi-Nakamoto

**Comment by Fractoshi-Nakamoto** [comment]
> Sorry, the website in the meta.json isn't yours. And please add your twitter or discount link. @Fractoshi-Nakamoto

Thanks! updated :)

**Comment by cloud6605** [comment]
The twitter isn't related to the collection. This is a personal collection, sorry, we don't accept it at present. @Fractoshi-Nakamoto

**Pull request closed without merging**
