### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Fractalbytes**

### CODE REVIEW

**Comment by Fractalbytes** [comment]
why i see message 1 worflow awaiting approval?
i'm the owner and creator

**Comment by Fractalbytes** [comment]
Please could you help me? Why I need workflow approval? @cloud6605

**Comment by cloud6605** [comment]
You need click on "Approve Run" to check if the json file is OK, then waiting for our review. @Fractalbytes

**Comment by cloud6605** [comment]
Now, the check failed. Please check your json file. All other is OK. Once you fix it, we'll merge it. @Fractalbytes 
image

**Comment by Fractalbytes** [comment]
@cloud6605 the fail of valid collection what does it means? Thanks

**Comment by Fractalbytes** [comment]
And where is this button of "approve run"? I cannot see in the screen @cloud6605

**Comment by cloud6605** [comment]
I already run it. Now, the issue is there is something wrong in your json file. You may check the details. @Fractalbytes 
image

**Comment by cloud6605** [comment]
I helped you fix it.
image
missed a ","

**Comment by Fractalbytes** [comment]
thanks @cloud6605 i'm sorry for the mistake...and thanks to correct it!
just to know for another time, where is the button of "approve run"?

**Pull request merged**
