### PR TITLE
Add Fractal Penguin Collection

### PR DESCRIPTION
**Pull request by Rb12me**
Added meta.json and inscriptions.json files for Fractal Penguin Collection.

### CODE REVIEW

**Comment by cloud6605** [comment]
image

And please use one of your inscription as the icon, modify the code "icon" as follwoing:
"inscription_idon":

**Comment by Rb12me** [comment]
> image
> 
> And please use one of your inscription as the icon, modify the code "icon" as follwoing: "inscription_idon":

Is this okay?

**Comment by cloud6605** [comment]
Quite well. Now, just remove the folder I marked. @Rb12me 
image

**Comment by Rb12me** [comment]
Done

**Pull request merged**
