### PR TITLE
Autofracs Listing

### PR DESCRIPTION
**Pull request by fractaldevs**
adding autofracs listing json

### CODE REVIEW

**Comment by cloud6605** [comment]
Please check your json file @fractaldevs

**Comment by cloud6605** [comment]
Sorry, it seems our indexer can't indify it's content correctly at present. Even if we list it, user can't see anything. Please wait for our dev to have a check. @fractaldevs

**Comment by fractaldevs** [comment]
> Sorry, it seems our indexer can't indify it's content correctly at present. Even if we list it, user can't see anything. Please wait for our dev to have a check. @fractaldevs

This collection is HTML code rather than a Image file

**Comment by cloud6605** [comment]
That's not the issue. It's we couldn't display this kind of NFT. Once we can disply it correctly, we'll list it. @fractaldevs

**Pull request merged**
