### PR TITLE
adding new collection

### PR DESCRIPTION
**Pull request by entra32**

### CODE REVIEW

**Comment by entra32** [comment]
@xhyhh0 Why i have the message "1 workflow awaiting approval"? i have followed instructions how to upload a collection

**Comment by cloud6605** [comment]
Sorry, there's something wrong in your code. Please let your dev to fix it first. You may click "Details" to learn the details about the error. @entra32 
image

**Comment by entra32** [comment]
@cloud6605 mistakes solved, please approve flow

**Comment by entra32** [comment]
Hi. Now solved. Please approve workflow. Thanks --Enviado con la aplicación GMX MailEl 14/10/24, 2:51 cloud6605 ***@***.***> escribió:

Sorry, there's something wrong in your code. Please let your dev to fix it first. You may click "Details" to learn the details about the error. @entra32
image.png (view on web)

**Comment by entra32** [comment]
@cloud6605 could you approve workflow please? Thanks

**Comment by entra32** [comment]
@cloud6605 @xhyhh0 can somebody help me please and start worflow?
why i cannot start it?

**Pull request merged**
