### PR TITLE
Create fractalcreatures

### PR DESCRIPTION
**Pull request by fbcreator**

### CODE REVIEW

**Review by fbcreator — COMMENTED** [review]
updated

**Comment by cloud6605** [comment]
image
You should create a folder first, then put meta.json and inscriptions.json under that folder. Then put the whole folder under "Collections" directory.

**Review by fbcreator — COMMENTED** [review]
moved to folder thanks

**Review by fbcreator — COMMENTED** [review]
folders changed and fixed

**Pull request closed without merging**
