### PR TITLE
Add JSON files for fractalrocks collection

### PR DESCRIPTION
**Pull request by elxsw**
Hey fam, i add a new data to a new collection, thanks in advance

Regards

### CODE REVIEW

**Comment by cloud6605** [comment]
can't open the twitter link. Please update it. @elxsw

**Comment by elxsw** [comment]
> can't open the twitter link. Please update it. @elxsw

Done sr

**Comment by elxsw** [comment]
> can't open the twitter link. Please update it. @elxsw

Hey sr, pls can you check our request?, regards

**Comment by cloud6605** [comment]
there's something wrong with your json file.

**Comment by cloud6605** [comment]
there's something wrong with your json file

**Comment by elxsw** [comment]
> there's something wrong with your json file

hey thank you, i change the name of the folder, pls check, regards

**Pull request merged**
