### PR TITLE
Update meta.json

### PR DESCRIPTION
**Pull request by fackjack001**
The original image used in the #GOOSE community collection’s #logo is relatively large and cannot be displayed! So I re-engraved a 400*400 one, which has been updated. Please help me merge it, thank you~~

### CODE REVIEW

**Comment by fackjack001** [comment]
Hello, please modify my pull request. My LOGO uses an engraving ID of 400*400.
Another thing is: Can the pictures of the #fractal #GOOSE collection be displayed like the #BTC mainnet? Please help me adjust it to the appropriate proportion on the front end, thank you~~
Here’s a comparison between #BTC and #FRACTAL
d747b56e7df6ab4defc5f7959367af1
bd3079361331eaf798850326f51e1dc

**Comment by cloud6605** [comment]
Our dev fixed it. Please have a check. @fackjack001

**Comment by fackjack001** [comment]
Looks good now.
thank you

cloud6605 ***@***.***>于2024年10月23日 周三下午12:57写道：

**Comment by fackjack001** [comment]
Let me reiterate that there is no project party for this project, only the
community! Our community is the first to publish this index! Since his
pictures that did not meet the specifications were not included, he
obstructed them in every possible way! In the end, you actually let a
pirated version be included in your collection. Where is the authenticity
and fairness?

#goose There is only the community, not the project party. The person who
claims to be the project party is a liar! Hey~~~

Shaniqua Tlucek ***@***.***>于2024年10月23日 周三下午1:25写道：

**Pull request merged**
