### PR TITLE
2 New Collection

### PR DESCRIPTION
**Pull request by Avecci-Claussen**
Securing 2 collection here for the community , artists are contributing to make the art. meanwhile, more inscriptions to come as soon as possible

### CODE REVIEW

**Comment by Avecci-Claussen** [comment]
i hope i dont get rejected again @cloud6605

**Comment by cloud6605** [comment]
The files are correct this time. But I'm sorry to say we accept collections submitted by community or project at present.
@Avecci-Claussen

**Comment by Avecci-Claussen** [comment]
isnt this a community project ?

**Comment by Avecci-Claussen** [comment]
im not profiting from this project nearly at all , the artists and those who are interested in using fractal assets are the ones who benefit

**Comment by Avecci-Claussen** [comment]
i beg you to not reject this one if it doesn't really bend any rules. i believe my collection is elligible

**Comment by cloud6605** [comment]
But it seems this collection isn't for ccommunity. Please check your twitter followers and telegram group.

**Comment by Avecci-Claussen** [comment]
i didn't make the collections , i inscribed them and listed them for users who agreed upon listing them

**Comment by Avecci-Claussen** [comment]
i hope you understand. you will give a chance to a community to be a part of fractal bitcoin.
i have physical community not just digital

**Comment by Avecci-Claussen** [comment]
the "fractal names" idea was a shared idea between the members as all the members participated in creating them.

as long as it got rejected , we thought of more compatible way to start connecting in with fractal bitcoin

**Comment by Avecci-Claussen** [comment]
you can merge or close man , in the end its your decision and i respect it

**Pull request closed without merging**
