### PR TITLE
Quantum drops

### PR DESCRIPTION
**Pull request by CapTake**
Quantum drops - on behalf of collection owner

### CODE REVIEW

**Comment by cloud6605** [comment]
Please update the icon. It doesn't have any relation to the collection. @CapTake

**Comment by CapTake** [comment]
Updated Icon, please merge :-)

**Comment by cloud6605** [comment]
can't open the icon @CapTake 
image

**Comment by CapTake** [comment]
https://i.ibb.co/QpvshCF/logo1.png - it's there, just rechecked, maybe there was a temporary outage? Please recheck

**Pull request closed without merging**
