### PR TITLE
Add New collection OP_CAT GENESIS

### PR DESCRIPTION
**Pull request by opcatgenesis**
Hello Support Team,

I hope this message finds you well. I would like to kindly request that my collection, OP_CAT GENESIS, be added to the marketplace. The collection consists of 444 exclusive pieces, and we are preparing for a public mint in the coming days.

Please let me know if you require any additional information or files to proceed. Thank you for your time and assistance in getting this collection live.

Best regards,

### CODE REVIEW

**Comment by cloud6605** [comment]
Hi, there's only one inscription in the inscriptions.json file. Please submit it once your collection is completely minted out. Thanks for understanding.

And there's something wrong in your code. Please have a check first.
image
 @

**Comment by opcatgenesis** [comment]
Hello Support Team,

I’ve made the necessary changes to my code as discussed. If there’s still an issue, could you please refer me to the specific area where the problem might be occurring?

Thank you for your continued support!

Best regards,

**Comment by cloud6605** [comment]
image

image
the correct code should be the following:
"inscription_icon": "xxxxx",
replace xxx with the inscription id. Don't add other information here.
@opcatgenesis

**Comment by opcatgenesis** [comment]
Capture d’écran 2024-10-19 143949
Hello Support Team,

I’ve made the necessary changes to my code as discussed.

**Comment by opcatgenesis** [comment]
Capture d’écran 2024-10-19 144108

**Pull request merged**
