### PR TITLE
Fractal Bored Ape Yacht Club

### PR DESCRIPTION
**Pull request by Fractal-BAYC**
Fractal Bored Ape Yacht Club is a collection of 5,000 unique NFTs on Fractal Bitcoin.

### CODE REVIEW

**Comment by cloud6605** [comment]
Hi, please let your dev check if there's something wrong with your inscriptions.json file, it can't pass the check. @Fractal-BAYC

**Comment by Fractal-BAYC** [comment]
Can you check again please! 
https://fractal.inscribenow.io/collections/b0f69c75e934bbcc/export.json?key=1329d19761b42fdc&unconfirmed=1

**Comment by cloud6605** [comment]
image

After submiting the new one, you also can click Approve and run button to check your file.

@Fractal-BAYC

**Comment by cloud6605** [comment]
Sorry, the same issue. Please let your dev to check it. There's an error in the code. You must fix it then resubmit it. @Fractal-BAYC 
image

**Comment by Fractal-BAYC** [comment]
> Sorry, the same issue. Please let your dev to check it. There's an error in the code. You must fix it then resubmit it. @Fractal-BAYC image

Dev said the JSON file is valid, and no syntax errors were detected.

**Comment by Fractal-BAYC** [comment]
The problem was in 

> Sorry, the same issue. Please let your dev to check it. There's an error in the code. You must fix it then resubmit it. @Fractal-BAYC image

I believe this is now working. Please verify.

**Comment by Fractal-BAYC** [comment]
> Sorry, the same issue. Please let your dev to check it. There's an error in the code. You must fix it then resubmit it. @Fractal-BAYC image

Please review this again

**Pull request merged**
