### PR TITLE
Add fractal ufo collection

### PR DESCRIPTION
**Pull request by IBW3B**
Fractal ufo collection on fractalbitcoin

### CODE REVIEW

**Comment by Avecci-Claussen** [comment]
cool ones , was the fee high for inscribing it ?

**Comment by IBW3B** [comment]
Thanks :) 

Approx 0.216fb for the fee (at the moment)

3d file size = 8ko

**Comment by Avecci-Claussen** [comment]
oh man thats pretty cool , im stuck at between 10 to 18 kb on my files , whatever i try to do after that fucks the quality :(

**Comment by IBW3B** [comment]
It's ok, my 3d models is not perfect :)

I choose simple low poly (without texturing if possible) to avoid the fee too big

I used Blender for export glb file (and max compress).

**Comment by Avecci-Claussen** [comment]
thank you so so much man. i understood i could do the same  , its really appreciated and i wish you best luck with your collection <3

**Comment by IBW3B** [comment]
You're welcome!

I'm new with Github and programming in general... I also need help ^^'

Hope this collections will be validated!

**Comment by Avecci-Claussen** [comment]
feel free to ask anything , i will also try my best to be helpful , and drop your fractal address , let me airdrop you some of my token : TLB "thelonelybit"

**Comment by IBW3B** [comment]
Thanks :)

D'ont hesitate too, you can contact me on X if you want @IBW3B

**Comment by Avecci-Claussen** [comment]
i tried finding you on telegram , here is mine @cyract

**Comment by cloud6605** [comment]
Don't use website link as an icon. It can be one of your inscriptions, or a link of an iamge. @IBW3B 
image

**Comment by cloud6605** [comment]
Please solve the conflict first. @IBW3B

**Pull request closed without merging**
