### PR TITLE
Update meta.json

### PR DESCRIPTION
**Pull request by Avecci-Claussen**
adding more links to the metadata

### CODE REVIEW

**Comment by Avecci-Claussen** [comment]
Hello @cloud6605 i wish you’re having a good time 

Fractal Aliens’s artist and @IBW3B would like to make a collaboration and list a shared collection.

the collection must be as a bundle , where NFTs can’t be bought separately , but can only bought as a bundle 

can the inscription.json be like this : 

  "collection": "Aliens and Spaceships",
  "items": [
    {
      "name": "shared bundle 01",
      "type": "bundle",
      "assets": [
        {
          "type": "alien",
          "name": "Alien 01",
          "inscription_id": "alien_inscription_id_01"
        },
        {
          "type": "spaceship",
          "name": "spaceshipname,
          "inscription_id": "spaceship_inscription_id_01"
        }
      ],

**Comment by Avecci-Claussen** [comment]
And would it look as a bundle showcasing both inscriptions together in the image ?

**Comment by cloud6605** [comment]
It's new feature, I'm afraid our marketplace can't support it at present.  Let me forwarded to our dev to have a check. 
And there's emojii in the name, I also need to check if we support it. @Avecci-Claussen

**Comment by Avecci-Claussen** [comment]
Thank you so much for your support ❤️ @cloud6605  I hope our UniSat marketplace offers more cool features as adding emojis in collection name and making bundles of objects that can’t be bought separately and only be bought as a bundle ! 🔥

**Comment by cloud6605** [comment]
hi, checked with our dev. At present, we're working on our infrua instruction, so we don't have effort to support the new feature. I'm so sorry. I've written it down, maybe we'll consider it once we get time. @Avecci-Claussen

**Comment by Avecci-Claussen** [comment]
@cloud6605 thank you so much for checking , I wish you’re doing well on it ! I’m also planning to drop this bundle collection in the future , so I would appreciate an update about it.

as well as for adding our community token TLB to pizzaswap

**Pull request merged**
