### PR TITLE
create collection "Fractal Names"

### PR DESCRIPTION
**Pull request by Avecci-Claussen**
Hi there , hereby providing my inscriptions and meta to create my collection of Fractal Names.

feel free to ask anything if needed

### CODE REVIEW

**Comment by Avecci-Claussen** [comment]
i would also like to get help on how to pick a slug because i tried everything according to the name and also a bit different but none of the checks was successful

**Comment by Avecci-Claussen** [comment]
I pray this meets the requirements , as it is a project for the community.

I will be probably airdropping some to random people for fun.

soon im listing brc20 token SPOILER : “TheLonelyBit”

airdrop on token also incoming

**Comment by Avecci-Claussen** [comment]
no answer about my collection ? been waiting for a while now :/

**Comment by cloud6605** [comment]
Thanks for your patience. We have marketplace for .fb domain. So we don't accept .fb domain collection. Please let your community to list them on our marketplace.  @Avecci-Claussen

**Comment by Avecci-Claussen** [comment]
@cloud6605 the names in providing in the collection are unique , the purpose of making the collection is to put the names of my community under 1 banner 

and I’m giving the names traits more then just the normal names that is already provided in UniSat marketplace.

why can’t I have a collection of my community names this is a bit unfair it feels

**Pull request closed without merging**
