### PR TITLE
(FMB)

### PR DESCRIPTION
**Pull request by fdot9999**
Please add

### CODE REVIEW

**Comment by cloud6605** [comment]
image

icon should be image of your collection, not the twitter link. And still no slug name here.
image

Attention: Please correct the errors in your meta.json file in local. Then create a folder "**fractal_maxi_bix**", put meta.json and inscriptions.json file under it. Finally upload the **whole folder** under "**Collections**" directory.

**Comment by cloud6605** [comment]
Quite well. You're nearly successful. The final step:
Create a **folder** named as **fracal_maxi_biz**, then put meta.json and inscriptions.json file in it, then upload the whole folder under "collections" directory.  @fdot9999 

The following is correct example.
image

**Comment by fdot9999** [comment]
jesus! it won't let me upload folder+ json only the jsons i don't know why

**Comment by cloud6605** [comment]
I close this request, you may try to pull a new request, then upload the whole folder.
BTW, is there only 2 inscriptions in your collection? @fdot9999

**Pull request closed without merging**
