### PR TITLE
Add collection FractalCube

### PR DESCRIPTION
**Pull request by FractalCubes**
Does recursive inscription affect operation?

### CODE REVIEW

**Comment by cloud6605** [comment]
Please check your json file. @FractalCubes 
And the twitter account is restricted.
image

**Comment by FractalCubes** [comment]
We have submitted the review for several days and may have been misunderstood and reported by the user

**Comment by FractalCubes** [comment]
Due to the review process, it has been postponed for a long time

**Comment by FractalCubes** [comment]
Can the document indicate where the problem lies?

**Pull request closed without merging**
