### PR TITLE
Fractal Pepes

### PR DESCRIPTION
**Pull request by LoveNFTs123**

### CODE REVIEW

**Comment by snoop-frog** [comment]
there is already a fractal pepe collection, https://x.com/fractalpepes 

this collection name might cause confusion with one of the highest volume trading collections on fractal

**Comment by cloud6605** [comment]
Please confirm this first. There's already the same collection. @LoveNFTs123

**Comment by LoveNFTs123** [comment]
His collection is "Flipped Fractal Pepes", but my collection is "Fractal Pepes". Pepe is a very popular theme, no one can monopoly it.

**Comment by snoop-frog** [comment]
This is one of two collection, one flipped Fractal Pepe and the other
fractal Pepe. While no one owns the name, calling a project something so
similar to the top trading project might mislead people.

**Pull request merged**
