### PR TITLE
ROCKFB 

### PR DESCRIPTION
**Pull request by FractalStone**

### CODE REVIEW

**Comment by FractalStone** [comment]
https://x.com/RockFractalBitc
Please add the Collection

**Comment by cloud6605** [comment]
Thanks for your effort. Just need a folder name now. @FractalStone 
image
and it seems there's something wrong with your twitter account. Please have a check.
image

**Comment by FractalStone** [comment]
The Tweeter account is from the language, it's ok, there's nothing wrong with it. But where can I find to rename the folder

**Comment by FractalStone** [comment]
can you show me where to rename the folder please

**Comment by cloud6605** [comment]
Totally wrong this time. You should created a folder named as ROCKFB under collections directory, then put the meta.json and inscriptions.json file under that folder. Please do your research, try more times. And just follow the step by step guids.(https://docs.unisat.io/fractal-services/how-to-submit-collection-in-github)
The following is correct.
image

**Pull request closed without merging**
