### PR TITLE
Inscriptions not showing - although it is merged & inedexed

### PR DESCRIPTION
**Pull request by Bloudraad**
This is exactly the same  SHROOMS inscriptions.json merged 4 days ago... 
However, The merged json new inscriptions not showing as part of the collection?
Kindly check it is there  66x new inscriptions in the actual Merged Json: 

47943e724977d686e8ff3f87eb0991ac5a5503c7d935a9ad07b01aa9476506f0i0
e340f03b8522a9b6fba3ccd03053325b0a0e4f59b213fe94074da20746d9cafdi0
2e40ff6aac0452c20f3a6cfe1a6efc6a1acd556775832629018009b73aa6a803i0
9fd22ef5fa251d712b1dd5fdddd9f1dbe0eea6d9367a051d7c15465e4d16bc23i0
d27c0cf7162fb55381ed7caf35dddee4417bcf5836aef73f66f7313c9ab86e30i0
dac8119aa15bd607277c4c96d9f761592c9ebaa73adec494a45664cb9b883224i0
db76a2fdd3523a69ee587977d737c93d004d96744a2fa9afc02c763a2b780a57i0
8432733dd76e0eb5f5de4e1f5e0bd6d6322e2374e57e0863716ed3e51c91bc42i0
78ed547d7883be6a68353781b9c1ace5bbd387752eeaacb9093de28978d4fa6ai0
1af5c7163895b0d3afc8683f21953ebb28065f19c9959ec385625524807ae900i0
7d5999ad7b18accb4d997938420fb87dde6b5f7f53b50e4512280f46f89a5f41i0
b236482964d5e7ba75db7843679b3d404fda581e0dd084ba1f5a2ded4b10021ai0
0335c9dea1b23d9b7dbdf1f2926ea25aedfd4d451a5d5bcd12c96292205b7220i0
60a947574f10eb77de520224ca8227629d9f6ead9b8e98be2129d85cdbbd33cai0
fbb904628518e88ddc9fe1393ad141ca1a91b21a7e18b6790d4fa0c89a1a3e1bi0
d7cdfa0aa6443d7b2561520f510ce7ff5c2150c0edebb1e74d513671f247a829i0
60ed52637420a6a578fa41b457a95bcbcefcf3e58b2cff70805bb7f06e48c5fci0
952face7b4dd055afd8d81b3db02223e0bb2177784beea3058bb59e2d2a78a32i0
f3940e2e6ab7d824423af30d9bb26fd3f973f961f75451f42ae126ac4dabaf7di0
1d0199368165a84c0e39c8cf127746adca60ddd8123e09fbe58f37e2299b422ci0
b2a30f48d57b53e212f586b3569e03996b536b230b369a961a2e718d13f05dd1i0
57c5669638743ee91578eec01826b2282e4a09e7dd98be6f48875d026d4c2e96i0
eb61a7bd16d7005e4f8407e08e6a8ed9ce4a88d419c4eec833335188fdf379cbi0
de6fc4730fd3030919b09dc9cb2d6f80014bdf699c58558167a9b5c3692982afi0
0f9e1944857865a7b5f7c51a19c32c1bb06404180a505db0687b19ea16950a7ci0
a606e6ade19284101cac47960dcf3b4b81374ff7f5fa3b1ff55954a11d892d19i0
962c3bb59625e9f83cda41239a116171c8c3690b98dff92e1cf7f873a207fb34i0
9000911b82bdab0c2bf0517943ec3f6649fba114a8b07ab268fc772b069b32cei0
00ba5358cd9996c281de987462980e3a56438436f8b8ae3cdabb6ccf4b1d3606i0
0cac40579550fa6524b0da00e6ae831f558001470ba677337007822c7d4647d1i0
658c0c6de992d0e32f41095adae63537990e688b6e2f4d5a9e2bc55b4ec08df7i0
2ff9345439773983412219192c7cc63594535ed1935b77f228dfa7588206f684i0
42e97c379c43735a2ad73b4d39550a293d8609516c258413cf10cf4a8bccb158i0
aaf6253d6a69561f3d0af905d0d589aa2e28bb28f1fb58fdba3d52e87defae31i0
b9c3f04f2e9f24b725c712e4f2aa2e59fbe9d12063ea012d651d59843ca082bdi0
89c8c6a03743f63c06d1c3f6ac0f27a66538388e7f208570c72392bdbb24b525i0
0dc6f1f1721bdd52ceafb4b9de0360793e4135dc59a72a17b5900ea2ddcf14b1i0
36841151b70f4183153c26a4ed8c59bd1b54fe34dfba8d928c29aa2582eca0f4i0
3dfb29837a3a48124021a94290bc131fa14dbb427a1074c035defbf5ac747081i0
b01b0612fd01bd48c61a8fdd459882251c3d344ec468f823c1ca11f0c3512e55i0
769b72b295ff66396e22415b1ddc4ca9571707e41d1e20fa4cb1a0d9bd1cb987i0
35f821261627f4c7771eeaff777937e102d734412797c452284929a6496f1f82i0
00c715226755852ac953b3f10333dc5ec2be88ecad5813e5bbc0d19be381bda0i0
f3ce2b68f3ca967ced2162a91791f47adc6e28731a2823618498cbe2333d3be8i0
ea8984fcb8d1700d9054c1e0bd99820e63fbb0261ef03fc9479ffaba7bab0559i0
f043dcaf8e4f4c09565688023ad84ce1b3f28265a615a57e1da48126440d48f8i0
d9e17a0091d82cef757ebedd043ae3c913aa360741fb92adeb160d1bbdf392dei0
fdf10abc1be6d8ad70b098e0ee86cd3ce756025f43b6afe1fbaa2cdcf79efce0i0
f9e7f59fa81664dfcfec990786253553831327b7c4f0d96bdac9e7bd20de1ad1i0
b47a9d51a951c38ff1ef29e2e252be5e3f96cba1caca6221b0a312c8e263e05ei0
091fc7f3b856b5ffa1911ba977c0b7c3937c155ebfc2f9f1ad415dbe8001b982i0
0025b42e831054a05bf926de29a8943ee085dab7957fd62ebb1bca79630bffe8i0
2ca3d75cda97f516049ac43a3971e786b315e3cb39230903c1329473128acf86i0
82080bee736cf3e27155b0384f6769bf5d364d249b4394315cd7ee1a3f45c3f5i0
9a2ffacacbd572aeef47444ea09814b6d346f20aa6d67223f18bda33307ec045i0
c07c465a849e228a6e951bb24f5b8645d3fc46df73a2793d7c2cb967f96173d7i0
51edf1c15b34119255dbbfe0c7457eab292ccd3afeb6d5b834debc88ac957f79i0
fe5d7960eda098b336a5f50c68ea5b85bc73cb50b881cd6e060693816c89a3a9i0
721947ccff429b0c98d5859bfb671a442e6025b37127c6fd4a162b87c94150aei0
d147d5e8d94095a05397bf7fbeb60e4c83460f03bcd8c26ed78164977cd5cf92i0
2a6caa0c6f50e583dd47bd0da20758fb76a51ddadedc159a1b1b2d43cdcf9d14i0
a5b4b0c8b3d5fb1fc38da316a237c80c600ea6d286a2630c2dd203ab871c134ai0
9cbdac645104a6af26e45b325822d3e301ff783cd5c38a9d84cd7c73c9129248i0
dd1e0b2d3b33ab3e6414ef384a94d681efa9348e606142338ee24e7b2c53259fi0
4f46f610c2c386e9b050df31b49ac9d5c939d5c4077914081b16d350ffbc8be0i0
d370d61f0f81d847bd03cf5db2b519f99205896fb52f37ce9941134198302c55i0

Same thing with our other collection fullmoon birds - The new birds merged 4 days ago not showing as part of collection....

### CODE REVIEW

**Comment by cloud6605** [comment]
Although it is merged, it may not update to the marketplace. I'll let our dev to have a check. @Bloudraad

**Comment by cloud6605** [comment]
hi, we just updated to marketplace, but the inscriptions you mentioned are not included. I searched them in your previous PR, and didn't find them at all. Please make sure you have updated your json file. Then upload in this PR.
image

**Comment by Bloudraad** [comment]
I do not understand - Both json are updated and actually in Unisat main branch?

For instance let us look at - SHROOMS COLLECTION
Below is the updated json that is in the actual Unisat Repository:

https://github.com/unisat-wallet/fractal-ordinals-collections/blob/main/collections/shrooms/inscriptions.json

But the last 66x entries are not displaying in the marketplace? although it shows in your main branch?
entries not displaying

**Comment by Bloudraad** [comment]
I did delete the repository and forked a new one at the time
Can this be the issue?
attached
[inscriptions.json](https://github.com/user-attachments/files/17614542/inscriptions.json)
the json as per your min branch

**Comment by cloud6605** [comment]
OK, I got it, our dev forgot to update it to the marketplace. We'll update it soon. Please wait with patience. @Bloudraad

**Comment by FRACTALTREX** [comment]
Please also the fullmoonbird json......
json merged but not updated - So it is a) FULLMOONBIRDS as well as b) SHROOMS

**Comment by cloud6605** [comment]
Hi, updated to the marketplace. Please have a check. @Bloudraad

**Pull request closed without merging**
