### PR TITLE
Added inscribed mints

### PR DESCRIPTION
**Pull request by hivebank**

### CODE REVIEW

**Comment by hivebank** [comment]
please publish on market. utility to come

**Comment by cloud6605** [comment]
the website link isn't correct. And please add your community, such as discord link etc. @hivebank 
image

**Comment by hivebank** [comment]
I don't have a community yet. the site there is showing the 3d model full screen i its beauty and details. The model is a standard glb so petentially useable in any standard 3d environments, like metaverses, future racing games etc.

**Comment by cloud6605** [comment]
Thanks for your reply. And we're sorry to say that we only accept collection submitted by community. @hivebank

**Comment by hivebank** [comment]
I AM THE COMMUNITY 
NOT FAKE 
NO WASHTRADE 
ADD IT NOW

**Pull request closed without merging**
