### PR TITLE
Create GLIZZY

### PR DESCRIPTION
**Pull request by alkanaka**
[export.json](https://github.com/user-attachments/files/17067986/export.json)

### CODE REVIEW

**Comment by alkanaka** [comment]
[meta.json](https://github.com/user-attachments/files/17069730/meta.json)

**Comment by alkanaka** [comment]
[inscription.json](https://github.com/user-attachments/files/17069784/inscription.json)

**Comment by alkanaka** [comment]
[inscription.json](https://github.com/user-attachments/files/17069825/inscription.json)

I updated the format to the example provided. First run at this.

**Comment by cloud6605** [comment]
Good job. You already created the folder Glizzy, then just upload your own meta.json and inscriptions.json file to this folder.

image

**Comment by alkanaka** [comment]
Still lost in the sauce. I keep trying to get both JSON files in that folder. Can I do that from my desktop or online. Sent from my iPhoneOn Sep 19, 2024, at 10:12 PM, cloud6605 ***@***.***> wrote:﻿
Good job. You already created the folder Glizzy, then just upload your own meta.json and inscriptions.json file to this folder.
image.png (view on web)

**Comment by cloud6605** [comment]
Yes, you may send it from you desktop.

**Comment by alkanaka** [comment]
Thanks I tried uploading again Sent from my iPhoneOn Sep 20, 2024, at 4:47 AM, cloud6605 ***@***.***> wrote:﻿
Yes, you may send it from you desktop.

**Review by alkanaka — COMMENTED** [review]
[inscription.json](https://github.com/user-attachments/files/17078747/inscription.json)
[meta.json](https://github.com/user-attachments/files/17078749/meta.json)

**Comment by cloud6605** [comment]
can't open twitter link.

**Comment by cloud6605** [comment]
you put in the wrong place. Please put it under your folder Glizzy. @alkanaka 
image

**Review by alkanaka — COMMENTED** [review]
Last change

**Comment by alkanaka** [comment]
I fixed it.

**Pull request closed without merging**
