### PR TITLE
Update meta.json

### PR DESCRIPTION
**Pull request by sam797979**

### CODE REVIEW

**Comment by cloud6605** [comment]
From the files, you didn't do any changes. Please don't submit the same PR. Thanks. @sam797979 
image

**Comment by sam797979** [comment]
I did.  I added an underscore to the name and slug fields and altered every entry of the inscriptions file

**Comment by sam797979** [comment]
the test result kept telling me the slug and name were different, identifying an underscore when there was not one. only way i could get round it was by adding the underscore it was looking for, then amend the inscriptions.json file to include the underscores

**Comment by sam797979** [comment]
this is all in an effort to get the collection showing on Unisat. the pull request was accepted yesterday with no issues, but the collection was not added to the marketplace
this is me trying to figure out why, and then fix it.

**Comment by cloud6605** [comment]
https://fractal.unisat.io/market/collection?collectionId=Ninja_Pizzas
It's already on our marketplace.
There isn't any issue. So no need to update it again.
In fact, after merging, it need our dev to list to marketplace, so there will be a delay. @sam797979

**Comment by sam797979** [comment]
oh okay, thank you so much, btw, I'm sorry if this is taking me a while to get the hang of this:/

**Pull request closed without merging**
